### ISSUE TITLE
[Daily Scrum] 2022.09.03 (토)

### ISSUE THREAD

**Issue by ikanic** [MacroUnit/Clone_Clock#1]
<details>
<summary><h2>오늘 할 일</h2></summary>
<div markdown="1">

#### 미뉴
- [ ] #2 
- [ ] #3

</div>
</details>

<details>
<summary><h2>ETC</h2></summary>
<div markdown="1">

#### 미뉴
- 오늘부터 열심히 달려봅시다~ 화이팅~!!

</div>
</details>

### 설명

Daily Scrum은 현재 작업 상황과 오늘 할 작업을 공유하는 중요한 시간입니다.
오늘은 프로젝트의 첫 날이라 작업 상황이 없으므로 아래에 Scrum Convention 첨부합니다.

#### 참고자료
[Scrum & Reflection Convention](https://github.com/MacroUnit/Clone_Clock/wiki/Scrum-&-Reflection-Convention)

**Comment by taek0622** [comment]
### 오늘 할 일
- [ ] 프로젝트 세팅
- [ ] 탭 뷰 추가
